### ISSUE TITLE
Multi-platform binary releases (goreleaser?)

### ISSUE THREAD

**Issue by orlangure** [orlangure/gocovsh#8]

**Comment by caarlos0** [comment]
this also fixes #9 

I'm happy to open a PR with the workflow and goreleaser config if you want :) 

PS: really loved this tool, was just wondering about writing something like this a couple of days ago 🙏

**Comment by orlangure** [comment]
Thanks for the kind words. It would be great if you could setup the release pipeline. I haven't thought about it much yet, so it's basically up to you.
